"""
MTA Schemas — Pydantic models for System B.

Every input schema is extremely self-descriptive (P1) so that the LLM Agent
can understand each field's business meaning directly from the OpenAPI spec.

The AgentResponse envelope (P2, P4) wraps all outputs with explicit state
and allowed next actions.
"""
from __future__ import annotations

from pydantic import BaseModel, Field
from typing import Any, List, Optional
from datetime import datetime


# ================================================================
#  MTA Envelope (P2 Machine-Readable, P4 Explicit State)
# ================================================================

class AgentResponse(BaseModel):
    """
    The universal response envelope for every MTA tool.

    Every tool in System B returns this structure so that the Agent always
    knows: (1) what data was returned, (2) the current state of the entity,
    (3) what tools it is allowed to call next, and (4) how to recover if
    something went wrong.
    """
    data: Any = Field(
        description="The actual business data returned by this tool. "
                    "Its schema varies per tool — refer to each tool's docstring for details."
    )
    current_state: str = Field(
        description="The explicit current state of the primary entity involved in this operation. "
                    "Examples: 'pending', 'paid', 'shipped', 'delivered', 'refund_pending', 'refunded', 'cancelled'. "
                    "For product operations: 'active', 'deleted'. For list operations: 'list_result'."
    )
    allowed_next_tools: List[str] = Field(
        description="An ordered list of tool names that the Agent is permitted to call next, "
                    "given the current state. The Agent MUST NOT call tools outside this list "
                    "for the same entity."
    )
    error_guidance: Optional[str] = Field(
        default=None,
        description="If an error occurred, this field contains a natural-language instruction "
                    "telling the Agent exactly how to fix the problem. If null, the operation succeeded."
    )


# ================================================================
#  Product Tool Schemas (P1 Self-Descriptive)
# ================================================================

class SearchProductsInput(BaseModel):
    """Input schema for the 'search_products' tool."""
    keyword: Optional[str] = Field(
        default=None,
        description="Optional keyword to filter products by name. "
                    "Leave empty or null to retrieve all products."
    )
    skip: int = Field(
        default=0,
        description="Number of records to skip for pagination. Default is 0 (start from the beginning)."
    )
    limit: int = Field(
        default=20,
        description="Maximum number of products to return. Default is 20. Maximum allowed is 100."
    )


class GetProductDetailsInput(BaseModel):
    """Input schema for the 'get_product_details' tool."""
    product_id: int = Field(
        ...,
        description="The unique integer ID of the product. "
                    "You can obtain this from the 'search_products' tool results."
    )


class CreateProductInput(BaseModel):
    """Input schema for the 'create_product' tool."""
    name: str = Field(
        ...,
        description="The display name of the product (e.g., 'iPhone 15 Pro'). Must not be empty."
    )
    description: Optional[str] = Field(
        default="",
        description="A textual description of the product. Can be empty."
    )
    price: float = Field(
        ...,
        description="The unit price of the product in CNY (Chinese Yuan). Must be greater than 0."
    )
    stock: int = Field(
        default=0,
        description="Initial stock quantity. Must be >= 0. Default is 0."
    )
    idempotency_key: str = Field(
        ...,
        description="A unique UUID string generated by you (the Agent) for this specific create action. "
                    "This prevents duplicate product creation if you retry the call. "
                    "Generate a new UUID for each distinct intention to create a product."
    )


class UpdateProductInput(BaseModel):
    """Input schema for the 'update_product' tool.

    PARTIAL UPDATE SEMANTICS: Only fields you explicitly provide will be modified.
    To keep a field unchanged, OMIT it entirely (do not pass null, do not pass empty string).
    Passing an empty string or 0 will OVERWRITE the current value.
    """
    product_id: int = Field(
        ...,
        description="The unique integer ID of the product to update. "
                    "Use 'get_product_details' or 'search_products' to find the correct ID first."
    )
    name: Optional[str] = Field(
        default=None,
        description="New product name. OMIT this field entirely to keep the current name unchanged. "
                    "Do NOT pass an empty string '' — that will overwrite the name with empty."
    )
    description: Optional[str] = Field(
        default=None,
        description="New product description. OMIT this field entirely to keep unchanged."
    )
    price: Optional[float] = Field(
        default=None,
        description="New unit price. Must be > 0 if provided. "
                    "OMIT this field entirely to keep the current price unchanged. "
                    "Do NOT pass 0 unless you really mean to set the price to zero."
    )
    stock: Optional[int] = Field(
        default=None,
        description="New stock quantity. Must be >= 0 if provided. "
                    "OMIT this field entirely to keep the current stock unchanged."
    )
    status: Optional[str] = Field(
        default=None,
        description="New product status. Valid values: 'NORMAL', 'LOCKED'. "
                    "OMIT this field entirely to keep the current status unchanged."
    )
    idempotency_key: str = Field(
        ...,
        description="A unique UUID string generated by you (the Agent) for this specific update action. "
                    "Prevents duplicate updates if you retry."
    )


class DeleteProductInput(BaseModel):
    """Input schema for the 'delete_product' tool."""
    product_id: int = Field(
        ...,
        description="The unique integer ID of the product to delete. "
                    "WARNING: This action is irreversible. Make sure you have confirmed with the user."
    )
    idempotency_key: str = Field(
        ...,
        description="A unique UUID string generated by you (the Agent) for this specific delete action. "
                    "Prevents duplicate deletions if you retry."
    )


# ================================================================
#  Order Tool Schemas (P1 Self-Descriptive)
# ================================================================

class OrderItemInput(BaseModel):
    """A single line item in an order."""
    product_id: int = Field(
        ...,
        description="The integer ID of the product to order. "
                    "You MUST verify this ID exists using 'search_products' or 'get_product_details' "
                    "before including it here."
    )
    quantity: int = Field(
        ...,
        description="The number of units to order. Must be >= 1. "
                    "Make sure the product has sufficient stock by checking 'get_product_details'."
    )


class CreateOrderInput(BaseModel):
    """Input schema for the 'create_order' tool."""
    customer_name: str = Field(
        ...,
        description="Full name of the customer placing the order. "
                    "DO NOT guess this — ask the user if not provided."
    )
    customer_email: Optional[str] = Field(
        default="",
        description="Email address of the customer. Used for order confirmation notifications. "
                    "Can be empty if the user declines to provide it."
    )
    shipping_address: Optional[str] = Field(
        default="",
        description="Complete shipping address including city, district, and street. "
                    "DO NOT guess — ask the user if not provided."
    )
    items: List[OrderItemInput] = Field(
        ...,
        description="A non-empty list of items to include in the order. "
                    "Each item must specify a valid product_id and quantity. "
                    "At least one item is required."
    )
    idempotency_key: str = Field(
        ...,
        description="A unique UUID string generated by you (the Agent) for this order creation. "
                    "If the same key is submitted again, the system will return the previously "
                    "created order instead of creating a duplicate."
    )


class SearchOrdersInput(BaseModel):
    """Input schema for the 'search_orders' tool."""
    status: Optional[str] = Field(
        default=None,
        description="Filter orders by status. Valid values: 'pending', 'paid', 'shipped', "
                    "'delivered', 'refund_pending', 'refunded', 'cancelled'. "
                    "Leave null to return orders in all statuses."
    )
    customer_name: Optional[str] = Field(
        default=None,
        description="Filter orders by customer name (partial match). Leave null for no filter."
    )
    skip: int = Field(
        default=0,
        description="Number of records to skip for pagination. Default is 0."
    )
    limit: int = Field(
        default=20,
        description="Maximum number of orders to return. Default is 20."
    )


class GetOrderDetailsInput(BaseModel):
    """Input schema for the 'get_order_details' tool."""
    order_id: int = Field(
        ...,
        description="The unique integer ID of the order. "
                    "You can obtain this from the 'search_orders' tool results."
    )


class UpdateOrderInput(BaseModel):
    """Input schema for the 'update_order' tool. Only works when order status is 'pending'."""
    order_id: int = Field(
        ...,
        description="The integer ID of the order to update. The order MUST be in 'pending' status. "
                    "Use 'get_order_details' to verify the current status before calling this tool."
    )
    customer_name: Optional[str] = Field(
        default=None,
        description="Updated customer name. Omit (null) to keep current value."
    )
    customer_email: Optional[str] = Field(
        default=None,
        description="Updated customer email. Omit (null) to keep current value."
    )
    shipping_address: Optional[str] = Field(
        default=None,
        description="Updated shipping address. Omit (null) to keep current value."
    )
    idempotency_key: str = Field(
        ...,
        description="A unique UUID for this update operation. Prevents duplicate updates on retry."
    )


class PayOrderInput(BaseModel):
    """Input schema for the 'pay_order' tool."""
    order_id: int = Field(
        ...,
        description="The integer ID of the order to pay. The order MUST be in 'pending' status. "
                    "Use 'get_order_details' to verify the status before calling this tool."
    )
    idempotency_key: str = Field(
        ...,
        description="A unique UUID for this payment operation. "
                    "CRITICAL: This prevents double-charging if you retry the call. "
                    "Always generate a fresh UUID for each distinct payment intention."
    )


class ShipOrderInput(BaseModel):
    """Input schema for the 'ship_order' tool."""
    order_id: int = Field(
        ...,
        description="The integer ID of the order to ship. The order MUST be in 'paid' status. "
                    "Verify via 'get_order_details' before calling."
    )
    idempotency_key: str = Field(
        ...,
        description="A unique UUID for this shipping operation. Prevents duplicate shipments on retry."
    )


class ConfirmDeliveryInput(BaseModel):
    """Input schema for the 'confirm_delivery' tool."""
    order_id: int = Field(
        ...,
        description="The integer ID of the order to confirm delivery. "
                    "The order MUST be in 'shipped' status. "
                    "Verify via 'get_order_details' before calling."
    )
    idempotency_key: str = Field(
        ...,
        description="A unique UUID for this delivery confirmation. Prevents duplicate confirmations."
    )


class CancelOrderInput(BaseModel):
    """Input schema for the 'cancel_order' tool."""
    order_id: int = Field(
        ...,
        description="The integer ID of the order to cancel. The order MUST be in 'pending' status. "
                    "Orders that have been paid or shipped cannot be cancelled — use 'apply_refund' instead."
    )
    cancel_reason: Optional[str] = Field(
        default=None,
        description="Optional reason for cancellation. Ask the user for a reason if appropriate."
    )
    idempotency_key: str = Field(
        ...,
        description="A unique UUID for this cancellation. Prevents duplicate cancellations."
    )


# ================================================================
#  Refund Tool Schemas (P1 Self-Descriptive)
# ================================================================

class ApplyRefundInput(BaseModel):
    """Input schema for the 'apply_refund' tool."""
    order_id: int = Field(
        ...,
        description="The integer ID of the order to request a refund for. "
                    "The order must be in 'paid', 'shipped', or 'delivered' status. "
                    "Use 'get_order_details' to verify before calling."
    )
    reason: str = Field(
        ...,
        description="The reason for requesting a refund. "
                    "DO NOT guess this. If the user hasn't provided a reason, "
                    "you MUST ask the user before calling this tool."
    )
    amount: float = Field(
        ...,
        description="The refund amount in CNY. Must be > 0 and must NOT exceed "
                    "the order's total_amount. Check the order total via 'get_order_details' first."
    )
    idempotency_key: str = Field(
        ...,
        description="A unique UUID for this refund application. "
                    "CRITICAL: Prevents duplicate refund requests if you retry the call."
    )


class SearchRefundsInput(BaseModel):
    """Input schema for the 'search_refunds' tool."""
    order_id: Optional[int] = Field(
        default=None,
        description="Filter refunds by order ID. Leave null to return all refunds."
    )
    status: Optional[str] = Field(
        default=None,
        description="Filter refunds by status. Valid values: 'pending', 'approved', 'rejected'. "
                    "Leave null for all statuses."
    )
    skip: int = Field(
        default=0,
        description="Number of records to skip for pagination."
    )
    limit: int = Field(
        default=20,
        description="Maximum number of refunds to return."
    )


class GetRefundDetailsInput(BaseModel):
    """Input schema for the 'get_refund_details' tool."""
    refund_id: int = Field(
        ...,
        description="The unique integer ID of the refund record. "
                    "You can obtain this from 'search_refunds' or from the 'apply_refund' response."
    )


class ApproveRefundInput(BaseModel):
    """Input schema for the 'approve_refund' tool."""
    refund_id: int = Field(
        ...,
        description="The integer ID of the refund to approve. The refund MUST be in 'pending' status. "
                    "Use 'get_refund_details' to verify before calling."
    )
    idempotency_key: str = Field(
        ...,
        description="A unique UUID for this approval action. Prevents double-approvals on retry."
    )


class RejectRefundInput(BaseModel):
    """Input schema for the 'reject_refund' tool."""
    refund_id: int = Field(
        ...,
        description="The integer ID of the refund to reject. The refund MUST be in 'pending' status. "
                    "Use 'get_refund_details' to verify before calling."
    )
    reject_reason: Optional[str] = Field(
        default=None,
        description="Reason for rejecting the refund. This will be communicated to the customer. "
                    "If the user (admin) hasn't provided a reason, ask them."
    )
    idempotency_key: str = Field(
        ...,
        description="A unique UUID for this rejection action. Prevents duplicate rejections on retry."
    )


# ================================================================
#  Response Data Sub-Models (for documentation clarity)
# ================================================================

class ProductData(BaseModel):
    """Structured representation of a product in tool responses."""
    id: int
    name: str
    description: str
    price: float
    stock: int
    status: str
    created_at: datetime

    model_config = {"from_attributes": True}


class OrderItemData(BaseModel):
    """Structured representation of an order line item."""
    id: int
    product_id: int
    quantity: int
    unit_price: float

    model_config = {"from_attributes": True}


class OrderData(BaseModel):
    """Structured representation of an order in tool responses."""
    id: int
    order_no: str
    customer_name: str
    customer_email: str
    status: str
    total_amount: float
    shipping_address: str
    created_at: datetime
    updated_at: datetime
    items: List[OrderItemData] = []

    model_config = {"from_attributes": True}


class OrderListItemData(BaseModel):
    """Compact order data for list views."""
    id: int
    order_no: str
    customer_name: str
    status: str
    total_amount: float
    created_at: datetime

    model_config = {"from_attributes": True}


class RefundData(BaseModel):
    """Structured representation of a refund in tool responses."""
    id: int
    refund_no: str
    order_id: int
    reason: str
    amount: float
    status: str
    created_at: datetime
    updated_at: datetime

    model_config = {"from_attributes": True}
